import { type ChangeEvent, useState } from "react";
import { type NextPage } from "next";
import Head from "next/head";

import { api } from "@/utils/api";

const urlRegex = new RegExp(
  "^((https?|ftp|file)://)?" + // protocol
    "((([a-zA-Z\\d]([a-zA-Z\\d-]*[a-zA-Z\\d])*)\\.)+[a-zA-Z]{2,}|" + // domain name
    "((\\d{1,3}\\.){3}\\d{1,3}))" + // OR ip (v4) address
    "(\\:\\d+)?(\\/[-a-zA-Z\\d%_.~+]*)*" + // port and path
    "(\\?[;&a-zA-Z\\d%_.~+=-]*)?" + // query string
    "(\\#[-a-zA-Z\\d_]*)?$" // fragment locator
);

const Home: NextPage = () => {
  const [url, setUrl] = useState<string>("");
  const instagramResult = api.instagram.imageFetcher.useQuery(
    { url },
    {
      enabled: false,
      refetchOnWindowFocus: false,
    }
  );

  const isUrlValid = !url || urlRegex.test(url);

  console.log(instagramResult.data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-primary to-secondary">
        <h1 className="mb-5 text-center text-[4.2rem] font-bold text-neutral md:text-[6rem]">
          IG Image Downloader
        </h1>
        <div className="align-center flex w-[50%] min-w-[25rem] flex-wrap justify-center gap-3 text-[3.2rem]">
          <input
            type="text"
            placeholder="Type here"
            className={`input-bordered input input-lg w-full max-w-md ${
              isUrlValid ? "input-neutral" : "input-error"
            }`}
            value={url}
            onChange={(e: ChangeEvent<HTMLInputElement>) =>
              setUrl(e.target.value)
            }
          />
          <button
            className="btn-accent btn-lg btn text-neutral"
            disabled={!isUrlValid}
            onClick={() => void instagramResult.refetch()}
          >
            GET the image!!
          </button>
        </div>
      </main>
    </>
  );
};

export default Home;
